In [36]:
type(drift)

pandas.core.series.Series

In [37]:
type(stdev)

pandas.core.series.Series

In [38]:
np.array(drift)

array([0.00035145])

In [39]:
drift.values

array([0.00035145])

In [41]:
norm.ppf(0.95)

1.6448536269514722

In [42]:
x = np.random.rand(10, 2)
x

array([[0.6635448 , 0.9655314 ],
       [0.17752634, 0.67588964],
       [0.12731798, 0.95315111],
       [0.09202447, 0.75722467],
       [0.89173569, 0.930387  ],
       [0.64810904, 0.7246568 ],
       [0.54619804, 0.29562469],
       [0.24287138, 0.79798929],
       [0.62418397, 0.04159085],
       [0.28619314, 0.66372043]])

In [43]:
norm.ppf(x)

array([[ 0.42215702,  1.81883116],
       [-0.92483318,  0.4562354 ],
       [-1.13916114,  1.67620635],
       [-1.32839112,  0.69740295],
       [ 1.23581154,  1.47867946],
       [ 0.38022026,  0.5967319 ],
       [ 0.11606134, -0.53702641],
       [-0.69709593,  0.83446072],
       [ 0.31648809, -1.73251619],
       [-0.56454059,  0.42263836]])

In [44]:
Z = norm.ppf(np.random.rand(10, 2))
Z

array([[-0.88629787, -0.07523336],
       [ 0.11200823,  0.32416139],
       [-0.46893707, -0.34106632],
       [ 0.57724602, -0.21813207],
       [ 0.67757317, -1.26107314],
       [-0.80382268, -0.11177436],
       [ 0.94421934,  0.23950195],
       [ 1.15173011,  1.74593064],
       [ 0.01621392,  1.28326988],
       [-0.4404186 , -0.16381687]])

In [45]:
t_intervals = 1000
iterations = 10

$$
    daily\_ returns = e^r 
$$
$$
    r = drift + stdev\cdot z
$$

In [46]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))

In [47]:
daily_returns

array([[0.99988513, 1.00796628, 1.00634992, ..., 1.00351774, 0.98117552,
        0.98045016],
       [1.00508656, 1.02020815, 1.00179511, ..., 0.99569183, 1.01647944,
        0.98957112],
       [1.00877515, 1.0175122 , 0.99594184, ..., 1.00776926, 0.99950519,
        0.99354404],
       ...,
       [0.99946475, 1.00111601, 1.01678604, ..., 0.99710681, 1.00515521,
        1.00846778],
       [1.00123344, 0.98849584, 0.99153783, ..., 0.98963593, 0.99611337,
        1.00879134],
       [0.99066991, 1.00562241, 1.01189628, ..., 0.99088042, 0.9958941 ,
        1.00686287]])